// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filecenter.proto

package filecenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件上传
type UploadReq struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TempFileLocation     string   `protobuf:"bytes,2,opt,name=tempFileLocation,proto3" json:"tempFileLocation,omitempty"`
	Task                 int64    `protobuf:"varint,3,opt,name=task,proto3" json:"task,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReq) Reset()         { *m = UploadReq{} }
func (m *UploadReq) String() string { return proto.CompactTextString(m) }
func (*UploadReq) ProtoMessage()    {}
func (*UploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{0}
}

func (m *UploadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReq.Unmarshal(m, b)
}
func (m *UploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReq.Marshal(b, m, deterministic)
}
func (m *UploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReq.Merge(m, src)
}
func (m *UploadReq) XXX_Size() int {
	return xxx_messageInfo_UploadReq.Size(m)
}
func (m *UploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReq proto.InternalMessageInfo

func (m *UploadReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadReq) GetTempFileLocation() string {
	if m != nil {
		return m.TempFileLocation
	}
	return ""
}

func (m *UploadReq) GetTask() int64 {
	if m != nil {
		return m.Task
	}
	return 0
}

func (m *UploadReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type UploadResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResp) Reset()         { *m = UploadResp{} }
func (m *UploadResp) String() string { return proto.CompactTextString(m) }
func (*UploadResp) ProtoMessage()    {}
func (*UploadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{1}
}

func (m *UploadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResp.Unmarshal(m, b)
}
func (m *UploadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResp.Marshal(b, m, deterministic)
}
func (m *UploadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResp.Merge(m, src)
}
func (m *UploadResp) XXX_Size() int {
	return xxx_messageInfo_UploadResp.Size(m)
}
func (m *UploadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UploadReq)(nil), "filecenter.UploadReq")
	proto.RegisterType((*UploadResp)(nil), "filecenter.UploadResp")
}

func init() { proto.RegisterFile("filecenter.proto", fileDescriptor_08c9044f220ed6aa) }

var fileDescriptor_08c9044f220ed6aa = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcb, 0xcc, 0x49,
	0x4d, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xd5, 0x73, 0x71, 0x86, 0x16, 0xe4, 0xe4, 0x27, 0xa6, 0x04, 0xa5, 0x16, 0x0a, 0x49, 0x71,
	0x71, 0x80, 0xa4, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c,
	0x21, 0x2d, 0x2e, 0x81, 0x92, 0xd4, 0xdc, 0x02, 0xb7, 0xcc, 0x9c, 0x54, 0x9f, 0xfc, 0xe4, 0xc4,
	0x92, 0xcc, 0xfc, 0x3c, 0x09, 0x26, 0xb0, 0x1a, 0x0c, 0x71, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xc4,
	0xe2, 0x6c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x30, 0x5b, 0x48, 0x8c, 0x8b, 0xad, 0x38,
	0x35, 0xb9, 0x28, 0xb5, 0x44, 0x82, 0x05, 0xac, 0x0b, 0xca, 0x53, 0xe2, 0xe1, 0xe2, 0x82, 0x39,
	0xa0, 0xb8, 0xc0, 0xc8, 0x9d, 0x8b, 0x0b, 0x64, 0x92, 0x33, 0xd8, 0x71, 0x42, 0x96, 0x5c, 0x6c,
	0x10, 0x39, 0x21, 0x51, 0x3d, 0x24, 0x5f, 0xc0, 0x1d, 0x2c, 0x25, 0x86, 0x4d, 0xb8, 0xb8, 0x40,
	0x89, 0x21, 0x89, 0x0d, 0xec, 0x55, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xdf, 0xd0,
	0xe2, 0xfe, 0x00, 0x00, 0x00,
}
