// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filecenter.proto

package filecenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件结构体
type File struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileLocation         string   `protobuf:"bytes,3,opt,name=fileLocation,proto3" json:"fileLocation,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

func (m *File) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// 文件上传
type UploadReq struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TempFileLocation     string   `protobuf:"bytes,2,opt,name=tempFileLocation,proto3" json:"tempFileLocation,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReq) Reset()         { *m = UploadReq{} }
func (m *UploadReq) String() string { return proto.CompactTextString(m) }
func (*UploadReq) ProtoMessage()    {}
func (*UploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{1}
}

func (m *UploadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReq.Unmarshal(m, b)
}
func (m *UploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReq.Marshal(b, m, deterministic)
}
func (m *UploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReq.Merge(m, src)
}
func (m *UploadReq) XXX_Size() int {
	return xxx_messageInfo_UploadReq.Size(m)
}
func (m *UploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReq proto.InternalMessageInfo

func (m *UploadReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadReq) GetTempFileLocation() string {
	if m != nil {
		return m.TempFileLocation
	}
	return ""
}

func (m *UploadReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type UploadResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileLocation         string   `protobuf:"bytes,2,opt,name=fileLocation,proto3" json:"fileLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResp) Reset()         { *m = UploadResp{} }
func (m *UploadResp) String() string { return proto.CompactTextString(m) }
func (*UploadResp) ProtoMessage()    {}
func (*UploadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{2}
}

func (m *UploadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResp.Unmarshal(m, b)
}
func (m *UploadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResp.Marshal(b, m, deterministic)
}
func (m *UploadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResp.Merge(m, src)
}
func (m *UploadResp) XXX_Size() int {
	return xxx_messageInfo_UploadResp.Size(m)
}
func (m *UploadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResp proto.InternalMessageInfo

func (m *UploadResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UploadResp) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

// 根据 id 获取文件
type FindFileReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileReq) Reset()         { *m = FindFileReq{} }
func (m *FindFileReq) String() string { return proto.CompactTextString(m) }
func (*FindFileReq) ProtoMessage()    {}
func (*FindFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{3}
}

func (m *FindFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileReq.Unmarshal(m, b)
}
func (m *FindFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileReq.Marshal(b, m, deterministic)
}
func (m *FindFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileReq.Merge(m, src)
}
func (m *FindFileReq) XXX_Size() int {
	return xxx_messageInfo_FindFileReq.Size(m)
}
func (m *FindFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileReq proto.InternalMessageInfo

func (m *FindFileReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindFileResp struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileResp) Reset()         { *m = FindFileResp{} }
func (m *FindFileResp) String() string { return proto.CompactTextString(m) }
func (*FindFileResp) ProtoMessage()    {}
func (*FindFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{4}
}

func (m *FindFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileResp.Unmarshal(m, b)
}
func (m *FindFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileResp.Marshal(b, m, deterministic)
}
func (m *FindFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileResp.Merge(m, src)
}
func (m *FindFileResp) XXX_Size() int {
	return xxx_messageInfo_FindFileResp.Size(m)
}
func (m *FindFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileResp proto.InternalMessageInfo

func (m *FindFileResp) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

// 根据权限 id 与任务 id 获取文件
type FindTaskFileReq struct {
	Task                 int64    `protobuf:"varint,1,opt,name=task,proto3" json:"task,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTaskFileReq) Reset()         { *m = FindTaskFileReq{} }
func (m *FindTaskFileReq) String() string { return proto.CompactTextString(m) }
func (*FindTaskFileReq) ProtoMessage()    {}
func (*FindTaskFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{5}
}

func (m *FindTaskFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTaskFileReq.Unmarshal(m, b)
}
func (m *FindTaskFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTaskFileReq.Marshal(b, m, deterministic)
}
func (m *FindTaskFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTaskFileReq.Merge(m, src)
}
func (m *FindTaskFileReq) XXX_Size() int {
	return xxx_messageInfo_FindTaskFileReq.Size(m)
}
func (m *FindTaskFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTaskFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindTaskFileReq proto.InternalMessageInfo

func (m *FindTaskFileReq) GetTask() int64 {
	if m != nil {
		return m.Task
	}
	return 0
}

func (m *FindTaskFileReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type FindTaskFileResp struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTaskFileResp) Reset()         { *m = FindTaskFileResp{} }
func (m *FindTaskFileResp) String() string { return proto.CompactTextString(m) }
func (*FindTaskFileResp) ProtoMessage()    {}
func (*FindTaskFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{6}
}

func (m *FindTaskFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTaskFileResp.Unmarshal(m, b)
}
func (m *FindTaskFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTaskFileResp.Marshal(b, m, deterministic)
}
func (m *FindTaskFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTaskFileResp.Merge(m, src)
}
func (m *FindTaskFileResp) XXX_Size() int {
	return xxx_messageInfo_FindTaskFileResp.Size(m)
}
func (m *FindTaskFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTaskFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindTaskFileResp proto.InternalMessageInfo

func (m *FindTaskFileResp) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "filecenter.File")
	proto.RegisterType((*UploadReq)(nil), "filecenter.UploadReq")
	proto.RegisterType((*UploadResp)(nil), "filecenter.UploadResp")
	proto.RegisterType((*FindFileReq)(nil), "filecenter.FindFileReq")
	proto.RegisterType((*FindFileResp)(nil), "filecenter.FindFileResp")
	proto.RegisterType((*FindTaskFileReq)(nil), "filecenter.FindTaskFileReq")
	proto.RegisterType((*FindTaskFileResp)(nil), "filecenter.FindTaskFileResp")
}

func init() { proto.RegisterFile("filecenter.proto", fileDescriptor_08c9044f220ed6aa) }

var fileDescriptor_08c9044f220ed6aa = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x69, 0x2c, 0xed, 0x6b, 0xd1, 0x30, 0x60, 0x0d, 0xf1, 0x83, 0xb2, 0x88, 0x14, 0x0f,
	0x3d, 0x54, 0x2f, 0x0a, 0xa2, 0x20, 0xf4, 0xa2, 0x78, 0x28, 0xf5, 0x07, 0xc4, 0x64, 0x85, 0xa5,
	0x1f, 0x59, 0xb3, 0x8b, 0xff, 0xd4, 0xff, 0x23, 0xbb, 0x69, 0xda, 0x24, 0x8d, 0xb7, 0xcc, 0xbc,
	0x37, 0xef, 0xcd, 0x9b, 0x0d, 0xfc, 0x2f, 0xb1, 0xe4, 0x31, 0x5f, 0x6b, 0x9e, 0x8d, 0x65, 0x96,
	0xea, 0x94, 0xb0, 0xeb, 0xb0, 0x1f, 0x78, 0x53, 0xb1, 0xe4, 0x74, 0x04, 0x57, 0x24, 0x81, 0x33,
	0x74, 0x46, 0xad, 0x99, 0x2b, 0x12, 0x0a, 0xd1, 0x31, 0xac, 0xf7, 0x68, 0xc5, 0x03, 0x77, 0xe8,
	0x8c, 0xba, 0xb3, 0x6d, 0x4d, 0x0c, 0x7d, 0xf3, 0xfd, 0x96, 0xc6, 0x91, 0x16, 0xe9, 0x3a, 0x68,
	0x59, 0xbc, 0xd2, 0xa3, 0x4b, 0x20, 0xce, 0x78, 0xa4, 0xf9, 0x5c, 0xac, 0x78, 0xe0, 0x59, 0x46,
	0xa9, 0xc3, 0x16, 0xe8, 0x7e, 0xc8, 0x65, 0x1a, 0x25, 0x33, 0xfe, 0x5d, 0x31, 0x73, 0x6a, 0x66,
	0x37, 0xf0, 0x35, 0x5f, 0xc9, 0x69, 0xd9, 0x30, 0x5f, 0x68, 0xaf, 0x4f, 0x03, 0xb4, 0x15, 0x8f,
	0x33, 0xae, 0x37, 0x2b, 0x6d, 0x2a, 0xf6, 0x0c, 0x14, 0x66, 0x4a, 0xee, 0x45, 0xad, 0xc7, 0x71,
	0xf7, 0xe3, 0xb0, 0x0b, 0xf4, 0xa6, 0x62, 0x9d, 0x18, 0x37, 0xb3, 0x70, 0x4d, 0x82, 0xdd, 0xa1,
	0xbf, 0x83, 0x95, 0xa4, 0x2b, 0x78, 0x66, 0xdc, 0x32, 0x7a, 0x13, 0x7f, 0x5c, 0x7a, 0x02, 0xcb,
	0xb1, 0x28, 0x7b, 0xc4, 0xb1, 0x99, 0x9a, 0x47, 0x6a, 0x51, 0x08, 0x13, 0x3c, 0x1d, 0xa9, 0xc5,
	0x46, 0xda, 0x7e, 0x97, 0x52, 0xb9, 0x95, 0x54, 0x0f, 0xf0, 0xab, 0xe3, 0x4a, 0xd2, 0x35, 0x0e,
	0x8d, 0xb4, 0x0a, 0x9c, 0x61, 0xab, 0xd1, 0x39, 0x87, 0x27, 0xbf, 0x0e, 0x60, 0xea, 0x17, 0x0b,
	0xd1, 0x3d, 0xda, 0xf9, 0x81, 0xe8, 0xa4, 0x3c, 0xb1, 0x7d, 0xa1, 0x70, 0xd0, 0xd4, 0x56, 0x92,
	0x1d, 0xd0, 0x13, 0x3a, 0x45, 0x74, 0x3a, 0xad, 0xda, 0x6d, 0xef, 0x15, 0x06, 0xcd, 0x80, 0x15,
	0x78, 0xcd, 0x6f, 0x57, 0xc4, 0xa0, 0xb3, 0x3a, 0xb7, 0x74, 0x9f, 0xf0, 0xfc, 0x7f, 0xd0, 0x88,
	0x7d, 0xb6, 0xed, 0x1f, 0x7e, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x75, 0x50, 0xec, 0x74, 0xf5,
	0x02, 0x00, 0x00,
}
