// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 任务结构体
type Task struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	TestType             string   `protobuf:"bytes,3,opt,name=testType,proto3" json:"testType,omitempty"`
	Client               string   `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	File                 *File    `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Result               int32    `protobuf:"varint,8,opt,name=result,proto3" json:"result,omitempty"`
	ResultDesc           string   `protobuf:"bytes,9,opt,name=resultDesc,proto3" json:"resultDesc,omitempty"`
	CreateTime           string   `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	StartTime            string   `protobuf:"bytes,11,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,12,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Task) GetTestType() string {
	if m != nil {
		return m.TestType
	}
	return ""
}

func (m *Task) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Task) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Task) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Task) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Task) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *Task) GetResultDesc() string {
	if m != nil {
		return m.ResultDesc
	}
	return ""
}

func (m *Task) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Task) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Task) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

// 文件结构体
type File struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileLocation         string   `protobuf:"bytes,3,opt,name=fileLocation,proto3" json:"fileLocation,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

func (m *File) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *File) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// 根据权限 id 获取任务
type FindTaskBySecretReq struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTaskBySecretReq) Reset()         { *m = FindTaskBySecretReq{} }
func (m *FindTaskBySecretReq) String() string { return proto.CompactTextString(m) }
func (*FindTaskBySecretReq) ProtoMessage()    {}
func (*FindTaskBySecretReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2}
}

func (m *FindTaskBySecretReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTaskBySecretReq.Unmarshal(m, b)
}
func (m *FindTaskBySecretReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTaskBySecretReq.Marshal(b, m, deterministic)
}
func (m *FindTaskBySecretReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTaskBySecretReq.Merge(m, src)
}
func (m *FindTaskBySecretReq) XXX_Size() int {
	return xxx_messageInfo_FindTaskBySecretReq.Size(m)
}
func (m *FindTaskBySecretReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTaskBySecretReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindTaskBySecretReq proto.InternalMessageInfo

func (m *FindTaskBySecretReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type FindTaskBySecretResp struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTaskBySecretResp) Reset()         { *m = FindTaskBySecretResp{} }
func (m *FindTaskBySecretResp) String() string { return proto.CompactTextString(m) }
func (*FindTaskBySecretResp) ProtoMessage()    {}
func (*FindTaskBySecretResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{3}
}

func (m *FindTaskBySecretResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTaskBySecretResp.Unmarshal(m, b)
}
func (m *FindTaskBySecretResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTaskBySecretResp.Marshal(b, m, deterministic)
}
func (m *FindTaskBySecretResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTaskBySecretResp.Merge(m, src)
}
func (m *FindTaskBySecretResp) XXX_Size() int {
	return xxx_messageInfo_FindTaskBySecretResp.Size(m)
}
func (m *FindTaskBySecretResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTaskBySecretResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindTaskBySecretResp proto.InternalMessageInfo

func (m *FindTaskBySecretResp) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

// 插入任务
type InsertTaskReq struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	TestType             string   `protobuf:"bytes,2,opt,name=testType,proto3" json:"testType,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	File                 int64    `protobuf:"varint,4,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTaskReq) Reset()         { *m = InsertTaskReq{} }
func (m *InsertTaskReq) String() string { return proto.CompactTextString(m) }
func (*InsertTaskReq) ProtoMessage()    {}
func (*InsertTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4}
}

func (m *InsertTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTaskReq.Unmarshal(m, b)
}
func (m *InsertTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTaskReq.Marshal(b, m, deterministic)
}
func (m *InsertTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTaskReq.Merge(m, src)
}
func (m *InsertTaskReq) XXX_Size() int {
	return xxx_messageInfo_InsertTaskReq.Size(m)
}
func (m *InsertTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTaskReq proto.InternalMessageInfo

func (m *InsertTaskReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *InsertTaskReq) GetTestType() string {
	if m != nil {
		return m.TestType
	}
	return ""
}

func (m *InsertTaskReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *InsertTaskReq) GetFile() int64 {
	if m != nil {
		return m.File
	}
	return 0
}

type InsertTaskResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTaskResp) Reset()         { *m = InsertTaskResp{} }
func (m *InsertTaskResp) String() string { return proto.CompactTextString(m) }
func (*InsertTaskResp) ProtoMessage()    {}
func (*InsertTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{5}
}

func (m *InsertTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTaskResp.Unmarshal(m, b)
}
func (m *InsertTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTaskResp.Marshal(b, m, deterministic)
}
func (m *InsertTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTaskResp.Merge(m, src)
}
func (m *InsertTaskResp) XXX_Size() int {
	return xxx_messageInfo_InsertTaskResp.Size(m)
}
func (m *InsertTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTaskResp proto.InternalMessageInfo

func (m *InsertTaskResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 推送任务
type PushTaskReq struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TaskType             string   `protobuf:"bytes,2,opt,name=taskType,proto3" json:"taskType,omitempty"`
	TaskFile             string   `protobuf:"bytes,3,opt,name=taskFile,proto3" json:"taskFile,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushTaskReq) Reset()         { *m = PushTaskReq{} }
func (m *PushTaskReq) String() string { return proto.CompactTextString(m) }
func (*PushTaskReq) ProtoMessage()    {}
func (*PushTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{6}
}

func (m *PushTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushTaskReq.Unmarshal(m, b)
}
func (m *PushTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushTaskReq.Marshal(b, m, deterministic)
}
func (m *PushTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushTaskReq.Merge(m, src)
}
func (m *PushTaskReq) XXX_Size() int {
	return xxx_messageInfo_PushTaskReq.Size(m)
}
func (m *PushTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushTaskReq proto.InternalMessageInfo

func (m *PushTaskReq) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *PushTaskReq) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *PushTaskReq) GetTaskFile() string {
	if m != nil {
		return m.TaskFile
	}
	return ""
}

func (m *PushTaskReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type PushTaskResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushTaskResp) Reset()         { *m = PushTaskResp{} }
func (m *PushTaskResp) String() string { return proto.CompactTextString(m) }
func (*PushTaskResp) ProtoMessage()    {}
func (*PushTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{7}
}

func (m *PushTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushTaskResp.Unmarshal(m, b)
}
func (m *PushTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushTaskResp.Marshal(b, m, deterministic)
}
func (m *PushTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushTaskResp.Merge(m, src)
}
func (m *PushTaskResp) XXX_Size() int {
	return xxx_messageInfo_PushTaskResp.Size(m)
}
func (m *PushTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushTaskResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Task)(nil), "manager.Task")
	proto.RegisterType((*File)(nil), "manager.File")
	proto.RegisterType((*FindTaskBySecretReq)(nil), "manager.FindTaskBySecretReq")
	proto.RegisterType((*FindTaskBySecretResp)(nil), "manager.FindTaskBySecretResp")
	proto.RegisterType((*InsertTaskReq)(nil), "manager.InsertTaskReq")
	proto.RegisterType((*InsertTaskResp)(nil), "manager.InsertTaskResp")
	proto.RegisterType((*PushTaskReq)(nil), "manager.PushTaskReq")
	proto.RegisterType((*PushTaskResp)(nil), "manager.PushTaskResp")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x26, 0x69, 0xfa, 0x37, 0xfd, 0xd1, 0x6a, 0x58, 0x16, 0x2b, 0x5a, 0x50, 0x30, 0x97, 0x5e,
	0xd8, 0xc3, 0x72, 0x42, 0x1c, 0x90, 0x10, 0x5a, 0x69, 0x25, 0x40, 0x90, 0xed, 0x0b, 0x98, 0x64,
	0x80, 0xa8, 0x6d, 0x12, 0x62, 0xe7, 0xb0, 0x2f, 0xc1, 0x3b, 0xf1, 0x28, 0xbc, 0x09, 0xb2, 0xe3,
	0xa4, 0x4e, 0xbb, 0xe5, 0xe6, 0xef, 0xfb, 0xc6, 0x99, 0xf1, 0xf7, 0x8d, 0x02, 0x8b, 0x9d, 0xc8,
	0xc5, 0x0f, 0xaa, 0xae, 0xca, 0xaa, 0x50, 0x05, 0x8e, 0x2d, 0xe4, 0x7f, 0x7c, 0x08, 0xd6, 0x42,
	0x6e, 0x70, 0x09, 0x7e, 0x96, 0x32, 0x2f, 0xf2, 0x56, 0x83, 0xd8, 0xcf, 0x52, 0xbc, 0x80, 0x91,
	0xa4, 0xa4, 0x22, 0xc5, 0xfc, 0xc8, 0x5b, 0x4d, 0x63, 0x8b, 0x30, 0x84, 0x89, 0x22, 0xa9, 0xd6,
	0xf7, 0x25, 0xb1, 0x81, 0x51, 0x3a, 0xac, 0xef, 0x24, 0xdb, 0x8c, 0x72, 0xc5, 0x82, 0xe6, 0x4e,
	0x83, 0x10, 0x21, 0x48, 0x49, 0x26, 0x6c, 0x68, 0x58, 0x73, 0xc6, 0x17, 0x10, 0x7c, 0xcf, 0xb6,
	0xc4, 0x46, 0x91, 0xb7, 0x9a, 0x5d, 0x2f, 0xae, 0xda, 0xf9, 0x6e, 0xb2, 0x2d, 0xc5, 0x46, 0x32,
	0x23, 0x28, 0xa1, 0x6a, 0xc9, 0xc6, 0x91, 0xb7, 0x1a, 0xc6, 0x16, 0x69, 0xbe, 0x22, 0x59, 0x6f,
	0x15, 0x9b, 0x34, 0x7c, 0x83, 0xf0, 0x39, 0x40, 0x73, 0xfa, 0xa0, 0x9b, 0x4d, 0x4d, 0x33, 0x87,
	0xd1, 0x7a, 0x52, 0x91, 0x50, 0xb4, 0xce, 0x76, 0xc4, 0xa0, 0xd1, 0xf7, 0x0c, 0x5e, 0xc2, 0x54,
	0x2a, 0x51, 0x29, 0x23, 0xcf, 0x8c, 0xbc, 0x27, 0x90, 0xc1, 0x98, 0xf2, 0xd4, 0x68, 0x73, 0xa3,
	0xb5, 0x90, 0xff, 0xf6, 0x20, 0xd0, 0x63, 0x1f, 0x79, 0x18, 0xc2, 0x44, 0x3f, 0xe4, 0xb3, 0xd8,
	0x91, 0x75, 0xb1, 0xc3, 0xc8, 0x61, 0xae, 0xcf, 0x1f, 0x8b, 0x44, 0xa8, 0xac, 0xc8, 0xad, 0x97,
	0x3d, 0xce, 0xc9, 0x20, 0xe8, 0x65, 0xd0, 0x7f, 0xc8, 0xf0, 0xf0, 0x21, 0xfc, 0x15, 0x3c, 0xbe,
	0xc9, 0xf2, 0x54, 0xe7, 0xfa, 0xfe, 0xfe, 0xce, 0xdc, 0x89, 0xe9, 0x97, 0xf3, 0x39, 0xcf, 0xfd,
	0x1c, 0x7f, 0x0b, 0xe7, 0xc7, 0xe5, 0xb2, 0xc4, 0x97, 0x30, 0x54, 0x42, 0x6e, 0x24, 0xf3, 0xa2,
	0x41, 0x2f, 0x23, 0x5d, 0x19, 0x37, 0x1a, 0xdf, 0xc0, 0xe2, 0x36, 0x97, 0x54, 0x29, 0x43, 0x9e,
	0xee, 0xd2, 0x5b, 0x1c, 0xff, 0x60, 0x71, 0xda, 0x05, 0x19, 0x38, 0x0b, 0x82, 0x76, 0x41, 0x02,
	0x63, 0xa7, 0x39, 0xf3, 0x08, 0x96, 0x6e, 0x33, 0x59, 0x1e, 0x5a, 0xce, 0x6b, 0x98, 0x7d, 0xa9,
	0xe5, 0x4f, 0x67, 0x18, 0x3d, 0xe6, 0x6d, 0x5b, 0x62, 0x91, 0x19, 0x46, 0xc8, 0x4d, 0x6f, 0x18,
	0x8b, 0x5b, 0x4d, 0x27, 0xda, 0x6d, 0xb8, 0xc5, 0xa7, 0x12, 0xe1, 0x4b, 0x98, 0xef, 0xdb, 0xca,
	0xf2, 0xfa, 0xaf, 0x07, 0x67, 0x77, 0x75, 0x59, 0x16, 0x95, 0xa2, 0xea, 0x53, 0x63, 0x1b, 0x7e,
	0x85, 0xb3, 0x43, 0x9f, 0xf1, 0xd2, 0x59, 0xfc, 0xa3, 0xc4, 0xc2, 0x67, 0xff, 0x51, 0x65, 0xc9,
	0x1f, 0xe1, 0x3b, 0x80, 0xbd, 0x21, 0x78, 0xd1, 0x95, 0xf7, 0x22, 0x09, 0x9f, 0x3e, 0xc8, 0x9b,
	0x0f, 0xbc, 0x81, 0x49, 0x3b, 0x38, 0x9e, 0x77, 0x65, 0x8e, 0x85, 0xe1, 0x93, 0x07, 0x58, 0x7d,
	0xf5, 0xdb, 0xc8, 0xfc, 0x4a, 0x5e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x97, 0x00, 0xa3,
	0x5b, 0x04, 0x00, 0x00,
}
