// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filecenter.proto

package filecenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件结构体
type File struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileLocation         string   `protobuf:"bytes,3,opt,name=fileLocation,proto3" json:"fileLocation,omitempty"`
	Task                 int64    `protobuf:"varint,4,opt,name=task,proto3" json:"task,omitempty"`
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

func (m *File) GetTask() int64 {
	if m != nil {
		return m.Task
	}
	return 0
}

func (m *File) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *File) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// 存入文件
type InsertFileReq struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertFileReq) Reset()         { *m = InsertFileReq{} }
func (m *InsertFileReq) String() string { return proto.CompactTextString(m) }
func (*InsertFileReq) ProtoMessage()    {}
func (*InsertFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{1}
}

func (m *InsertFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertFileReq.Unmarshal(m, b)
}
func (m *InsertFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertFileReq.Marshal(b, m, deterministic)
}
func (m *InsertFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertFileReq.Merge(m, src)
}
func (m *InsertFileReq) XXX_Size() int {
	return xxx_messageInfo_InsertFileReq.Size(m)
}
func (m *InsertFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertFileReq proto.InternalMessageInfo

func (m *InsertFileReq) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type InsertFileResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertFileResp) Reset()         { *m = InsertFileResp{} }
func (m *InsertFileResp) String() string { return proto.CompactTextString(m) }
func (*InsertFileResp) ProtoMessage()    {}
func (*InsertFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{2}
}

func (m *InsertFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertFileResp.Unmarshal(m, b)
}
func (m *InsertFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertFileResp.Marshal(b, m, deterministic)
}
func (m *InsertFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertFileResp.Merge(m, src)
}
func (m *InsertFileResp) XXX_Size() int {
	return xxx_messageInfo_InsertFileResp.Size(m)
}
func (m *InsertFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_InsertFileResp proto.InternalMessageInfo

func (m *InsertFileResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 根据 id 获取文件
type FindFileByIdReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileByIdReq) Reset()         { *m = FindFileByIdReq{} }
func (m *FindFileByIdReq) String() string { return proto.CompactTextString(m) }
func (*FindFileByIdReq) ProtoMessage()    {}
func (*FindFileByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{3}
}

func (m *FindFileByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileByIdReq.Unmarshal(m, b)
}
func (m *FindFileByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileByIdReq.Marshal(b, m, deterministic)
}
func (m *FindFileByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileByIdReq.Merge(m, src)
}
func (m *FindFileByIdReq) XXX_Size() int {
	return xxx_messageInfo_FindFileByIdReq.Size(m)
}
func (m *FindFileByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileByIdReq proto.InternalMessageInfo

func (m *FindFileByIdReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindFileByIdResp struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileByIdResp) Reset()         { *m = FindFileByIdResp{} }
func (m *FindFileByIdResp) String() string { return proto.CompactTextString(m) }
func (*FindFileByIdResp) ProtoMessage()    {}
func (*FindFileByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{4}
}

func (m *FindFileByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileByIdResp.Unmarshal(m, b)
}
func (m *FindFileByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileByIdResp.Marshal(b, m, deterministic)
}
func (m *FindFileByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileByIdResp.Merge(m, src)
}
func (m *FindFileByIdResp) XXX_Size() int {
	return xxx_messageInfo_FindFileByIdResp.Size(m)
}
func (m *FindFileByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileByIdResp proto.InternalMessageInfo

func (m *FindFileByIdResp) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

// 根据任务 id 和权限 id 获取文件
type FindFileByTaskAndSecretReq struct {
	Task                 int64    `protobuf:"varint,1,opt,name=task,proto3" json:"task,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileByTaskAndSecretReq) Reset()         { *m = FindFileByTaskAndSecretReq{} }
func (m *FindFileByTaskAndSecretReq) String() string { return proto.CompactTextString(m) }
func (*FindFileByTaskAndSecretReq) ProtoMessage()    {}
func (*FindFileByTaskAndSecretReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{5}
}

func (m *FindFileByTaskAndSecretReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileByTaskAndSecretReq.Unmarshal(m, b)
}
func (m *FindFileByTaskAndSecretReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileByTaskAndSecretReq.Marshal(b, m, deterministic)
}
func (m *FindFileByTaskAndSecretReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileByTaskAndSecretReq.Merge(m, src)
}
func (m *FindFileByTaskAndSecretReq) XXX_Size() int {
	return xxx_messageInfo_FindFileByTaskAndSecretReq.Size(m)
}
func (m *FindFileByTaskAndSecretReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileByTaskAndSecretReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileByTaskAndSecretReq proto.InternalMessageInfo

func (m *FindFileByTaskAndSecretReq) GetTask() int64 {
	if m != nil {
		return m.Task
	}
	return 0
}

func (m *FindFileByTaskAndSecretReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type FindFileByTaskAndSecretResp struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindFileByTaskAndSecretResp) Reset()         { *m = FindFileByTaskAndSecretResp{} }
func (m *FindFileByTaskAndSecretResp) String() string { return proto.CompactTextString(m) }
func (*FindFileByTaskAndSecretResp) ProtoMessage()    {}
func (*FindFileByTaskAndSecretResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c9044f220ed6aa, []int{6}
}

func (m *FindFileByTaskAndSecretResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindFileByTaskAndSecretResp.Unmarshal(m, b)
}
func (m *FindFileByTaskAndSecretResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindFileByTaskAndSecretResp.Marshal(b, m, deterministic)
}
func (m *FindFileByTaskAndSecretResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindFileByTaskAndSecretResp.Merge(m, src)
}
func (m *FindFileByTaskAndSecretResp) XXX_Size() int {
	return xxx_messageInfo_FindFileByTaskAndSecretResp.Size(m)
}
func (m *FindFileByTaskAndSecretResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindFileByTaskAndSecretResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindFileByTaskAndSecretResp proto.InternalMessageInfo

func (m *FindFileByTaskAndSecretResp) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "filecenter.File")
	proto.RegisterType((*InsertFileReq)(nil), "filecenter.InsertFileReq")
	proto.RegisterType((*InsertFileResp)(nil), "filecenter.InsertFileResp")
	proto.RegisterType((*FindFileByIdReq)(nil), "filecenter.FindFileByIdReq")
	proto.RegisterType((*FindFileByIdResp)(nil), "filecenter.FindFileByIdResp")
	proto.RegisterType((*FindFileByTaskAndSecretReq)(nil), "filecenter.FindFileByTaskAndSecretReq")
	proto.RegisterType((*FindFileByTaskAndSecretResp)(nil), "filecenter.FindFileByTaskAndSecretResp")
}

func init() { proto.RegisterFile("filecenter.proto", fileDescriptor_08c9044f220ed6aa) }

var fileDescriptor_08c9044f220ed6aa = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0xb5, 0x14, 0xf2, 0x73, 0x44, 0x24, 0x63, 0xa2, 0x6b, 0x31, 0xa6, 0x6e, 0x0c, 0x72,
	0xe2, 0x80, 0x31, 0xf1, 0xaa, 0x06, 0x22, 0xd1, 0x78, 0x00, 0xbe, 0x40, 0x6d, 0xc7, 0x64, 0x03,
	0xb4, 0xeb, 0xee, 0x7a, 0xf0, 0x93, 0x78, 0xf7, 0x93, 0x9a, 0x5d, 0xff, 0xd0, 0x12, 0x9a, 0x70,
	0xdb, 0x99, 0xf7, 0xde, 0xbc, 0x99, 0x97, 0x2c, 0xb4, 0x5f, 0xc4, 0x82, 0x12, 0xca, 0x0c, 0xa9,
	0xbe, 0x54, 0xb9, 0xc9, 0x11, 0x56, 0x1d, 0xfe, 0xe9, 0x41, 0x30, 0x12, 0x0b, 0xc2, 0x16, 0xf8,
	0x22, 0x65, 0x5e, 0xe4, 0xf5, 0x6a, 0x13, 0x5f, 0xa4, 0x18, 0xc2, 0x7f, 0x4b, 0x7b, 0x8a, 0x97,
	0xc4, 0xfc, 0xc8, 0xeb, 0xed, 0x4c, 0xfe, 0x6a, 0xe4, 0xd0, 0xb4, 0xef, 0xc7, 0x3c, 0x89, 0x8d,
	0xc8, 0x33, 0x56, 0x73, 0x78, 0xa9, 0x87, 0x08, 0x81, 0x89, 0xf5, 0x9c, 0x05, 0x6e, 0xa2, 0x7b,
	0xe3, 0x21, 0x34, 0x34, 0x25, 0x8a, 0x0c, 0xab, 0x3b, 0xc5, 0x4f, 0x85, 0xa7, 0x00, 0x89, 0xa2,
	0xd8, 0xd0, 0x4c, 0x2c, 0x89, 0x35, 0x1c, 0x56, 0xe8, 0xf0, 0x2b, 0xd8, 0x1b, 0x67, 0x9a, 0x94,
	0xb1, 0x9b, 0x4e, 0xe8, 0x15, 0xcf, 0x21, 0xb0, 0x66, 0x6e, 0xdd, 0xdd, 0x41, 0xbb, 0x5f, 0x38,
	0xd1, 0x51, 0x1c, 0xca, 0x23, 0x68, 0x15, 0x65, 0x5a, 0xae, 0x1f, 0xc9, 0xcf, 0x60, 0x7f, 0x24,
	0xb2, 0xd4, 0xe2, 0xb7, 0xef, 0xe3, 0xd4, 0x8e, 0x5e, 0xa7, 0x5c, 0x43, 0xbb, 0x4c, 0xd1, 0x72,
	0x4b, 0xfb, 0x7b, 0x08, 0x57, 0xca, 0x59, 0xac, 0xe7, 0x37, 0x59, 0x3a, 0x75, 0x07, 0x5b, 0x9f,
	0xdf, 0x7c, 0xbc, 0x8d, 0xf9, 0xf8, 0xc5, 0x7c, 0xf8, 0x10, 0x3a, 0x95, 0x93, 0xb4, 0xc4, 0x2e,
	0xd4, 0xad, 0xa1, 0x66, 0x5e, 0x54, 0xdb, 0xb8, 0xcf, 0x37, 0x3c, 0xf8, 0xf0, 0xe1, 0x60, 0xfa,
	0x26, 0x65, 0xae, 0x0c, 0x29, 0x0b, 0xdc, 0x39, 0x0e, 0x0e, 0x01, 0x56, 0x39, 0xe1, 0x71, 0x51,
	0x5e, 0x8a, 0x3d, 0x0c, 0xab, 0x20, 0x2d, 0xf9, 0x3f, 0x7c, 0x80, 0x66, 0x31, 0x29, 0xec, 0x94,
	0xf7, 0x28, 0xc5, 0x1c, 0x9e, 0x54, 0x83, 0x6e, 0xd8, 0x02, 0x8e, 0x2a, 0x4e, 0xc6, 0xee, 0x66,
	0xe9, 0x7a, 0xc2, 0xe1, 0xc5, 0x56, 0x3c, 0xeb, 0xf6, 0xdc, 0x70, 0x1f, 0xe3, 0xf2, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x04, 0xc5, 0x09, 0x94, 0x2c, 0x03, 0x00, 0x00,
}
