// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建任务
type CreateTaskReq struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	TestType             string   `protobuf:"bytes,2,opt,name=testType,proto3" json:"testType,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	FileName             string   `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileLocation         string   `protobuf:"bytes,5,opt,name=fileLocation,proto3" json:"fileLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskReq) Reset()         { *m = CreateTaskReq{} }
func (m *CreateTaskReq) String() string { return proto.CompactTextString(m) }
func (*CreateTaskReq) ProtoMessage()    {}
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *CreateTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskReq.Unmarshal(m, b)
}
func (m *CreateTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskReq.Marshal(b, m, deterministic)
}
func (m *CreateTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskReq.Merge(m, src)
}
func (m *CreateTaskReq) XXX_Size() int {
	return xxx_messageInfo_CreateTaskReq.Size(m)
}
func (m *CreateTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskReq proto.InternalMessageInfo

func (m *CreateTaskReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateTaskReq) GetTestType() string {
	if m != nil {
		return m.TestType
	}
	return ""
}

func (m *CreateTaskReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateTaskReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CreateTaskReq) GetFileLocation() string {
	if m != nil {
		return m.FileLocation
	}
	return ""
}

type CreateTaskResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResp) Reset()         { *m = CreateTaskResp{} }
func (m *CreateTaskResp) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResp) ProtoMessage()    {}
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *CreateTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResp.Unmarshal(m, b)
}
func (m *CreateTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResp.Marshal(b, m, deterministic)
}
func (m *CreateTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResp.Merge(m, src)
}
func (m *CreateTaskResp) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResp.Size(m)
}
func (m *CreateTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResp proto.InternalMessageInfo

func (m *CreateTaskResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateTaskReq)(nil), "manager.CreateTaskReq")
	proto.RegisterType((*CreateTaskResp)(nil), "manager.CreateTaskResp")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xa6, 0x33,
	0x72, 0xf1, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x86, 0x24, 0x16, 0x67, 0x07, 0xa5, 0x16, 0x0a,
	0x89, 0x71, 0xb1, 0x15, 0xa7, 0x26, 0x17, 0xa5, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x41, 0x79, 0x42, 0x52, 0x5c, 0x1c, 0x25, 0xa9, 0xc5, 0x25, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x4c,
	0x60, 0x19, 0x38, 0x5f, 0x48, 0x88, 0x8b, 0x25, 0x25, 0xb5, 0x38, 0x59, 0x82, 0x19, 0x2c, 0x0e,
	0x66, 0x83, 0xd4, 0xa7, 0x65, 0xe6, 0xa4, 0xfa, 0x25, 0xe6, 0xa6, 0x4a, 0xb0, 0x40, 0xd4, 0xc3,
	0xf8, 0x42, 0x4a, 0x5c, 0x3c, 0x20, 0xb6, 0x4f, 0x7e, 0x72, 0x62, 0x49, 0x66, 0x7e, 0x9e, 0x04,
	0x2b, 0x58, 0x1e, 0x45, 0x4c, 0x49, 0x81, 0x8b, 0x0f, 0xd9, 0x61, 0xc5, 0x05, 0x42, 0x7c, 0x5c,
	0x4c, 0x99, 0x29, 0x60, 0x57, 0x31, 0x07, 0x31, 0x65, 0xa6, 0x18, 0x79, 0x71, 0xb1, 0xfb, 0x42,
	0xbc, 0x21, 0x64, 0xcf, 0xc5, 0x85, 0x50, 0x2c, 0x24, 0xa6, 0x07, 0xf3, 0x2d, 0x8a, 0xd7, 0xa4,
	0xc4, 0xb1, 0x8a, 0x17, 0x17, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xc3, 0xc5, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x04, 0x16, 0x58, 0xb3, 0x28, 0x01, 0x00, 0x00,
}
